### PR TITLE
Add ability to manipulate indexed db

### LINKED ISSUE #39: Add ability to manipulate  `indexDB`
### Subject

db

### Description

The next step in #38 and #37 is to add functionality to manipulate the `indexDB`.

- Function to get `theme`.
- Function to write `theme`.
- Function to get `theme` for a specific component.
- Function to write `theme` for a specific component.

### Are you willing to participate in the development of this feature and create a pull request?

None

### PR DESCRIPTION
**Pull request by odendayoko**
Closes #39 

## Description
Based on the [DB design](https://github.com/yamada-ui/yamada-theme/issues/38), functions are added to retrieve and store data from indexedDB.

## New behavior
- Can create database in indexedDB
- Theme can be named and saved.
- Saved Theme can be retrieved.
- Theme can be named and Theme for a specific component can be saved
- Can retrieve the Theme of a specific component from a saved Theme.

## Is this a breaking change (Yes/No):
No

## Additional Information
The put() method of the [IDBObjectStore](https://developer.mozilla.org/en-US/docs/Web/API/IDBObjectStore) interface updates a given record in a database, or inserts a new record if the given item does not already exist.

### CODE REVIEW

**Review by 108yen — COMMENTED** [review]
Move to `utils/indexdb.ts`.

**Comment by odendayoko** [comment]
@108yen 
After changing the file, I was wondering if I should use `indexeddb.ts` or `indexed-db.ts` instead of `indexedDB.ts`?
Is the file name a kebab case?

**Comment by 108yen** [comment]
> @108yen After changing the file, I was wondering if I should use `indexeddb.ts` or `indexed-db.ts` instead of `indexedDB.ts`? Is the file name a kebab case?

It may be changed later, but for now let's use `indexeddb.ts`.

**Comment by odendayoko** [comment]
> > @108yen After changing the file, I was wondering if I should use `indexeddb.ts` or `indexed-db.ts` instead of `indexedDB.ts`? Is the file name a kebab case?
> 
> It may be changed later, but for now let's use `indexeddb.ts`.

OK!! Fixed👍

**Pull request merged**
