### PR TITLE
feat: added spellcheck

### PR DESCRIPTION
**Pull request by 108yen**
## Description

Add `spellcheck` script and `cspell.json` for spell checking.
## Current behavior (updates)

NIL
## New behavior

NIL
## Is this a breaking change (Yes/No):

No

### CODE REVIEW

**Comment by koralle** [comment]
@108yen 

Do you run spell checks within the pre-commit hook? If needed, I can set it up.

**Comment by hirotomoyamada** [comment]
@koralle @108yen 

> Do you run spell checks within the pre-commit hook? If needed, I can set it up.

Let's discuss that with the entire Yamada UI.

**Comment by 108yen** [comment]
@koralle 

> Do you run spell checks within the pre-commit hook? If needed, I can set it up.

Let's do it. If it bothers you, we'll remove it then.
CI will incorporate it.

**Comment by 108yen** [comment]
@hirotomoyamada 
Is there any problem to try with the Yamada Theme?

**Comment by hirotomoyamada** [comment]
@108yen 

No problem. I just don't think it will work.The reason is that spell check is not perfect.

**Review by koralle — APPROVED** [review]

**Pull request merged**
